name: Auto Tagging

on:
  push:
    branches:
      - main
    paths:
      - .version

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get version from file
        id: get_version
        run: echo "::set-output name=version::$(cat .version)"

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create tag
        id: create_tag
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}
